// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using simplified_picpay.Data;

#nullable disable

namespace simplified_picpay.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250924201546_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("simplified_picpay.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("current_balance");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_accounts_email");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("simplified_picpay.Models.Storekeeper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar")
                        .HasColumnName("cnpj");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("CNPJ")
                        .IsUnique()
                        .HasDatabaseName("ux_storekeepers_cnpj");

                    b.ToTable("storekeepers", (string)null);
                });

            modelBuilder.Entity("simplified_picpay.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar")
                        .HasColumnName("cpf");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("CPF")
                        .IsUnique()
                        .HasDatabaseName("ux_users_cpf");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("simplified_picpay.Models.Storekeeper", b =>
                {
                    b.HasOne("simplified_picpay.Models.Account", "Account")
                        .WithOne("Storekeeper")
                        .HasForeignKey("simplified_picpay.Models.Storekeeper", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_storekeepers_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("simplified_picpay.Models.User", b =>
                {
                    b.HasOne("simplified_picpay.Models.Account", "Account")
                        .WithOne("User")
                        .HasForeignKey("simplified_picpay.Models.User", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("simplified_picpay.Models.Account", b =>
                {
                    b.Navigation("Storekeeper");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
